import React, { useState, useEffect } from "react";

type Section = {
    id: string;
    title: string;
    content: string;
};

const sections: Section[] = [
    {
        id: "bab1",
        title: "Bab 1 Pendahuluan",
        content:
            "Bab ini berisi latar belakang penelitian, rumusan masalah, tujuan penelitian, manfaat penelitian, dan sistematika penulisan skripsi. Latar belakang penelitian menjelaskan alasan utama mengapa penelitian ini dilakukan serta fenomena atau masalah yang menjadi dasar penelitian. Dalam bagian ini, dijelaskan bagaimana permasalahan yang ada dapat berdampak signifikan terhadap bidang yang diteliti.\n\n" +
            "Rumusan masalah dalam penelitian ini dirancang untuk memperjelas aspek-aspek yang akan dikaji dan pertanyaan penelitian yang akan dijawab. Hal ini penting untuk memastikan bahwa penelitian memiliki arah yang jelas dan dapat menghasilkan temuan yang relevan. Tujuan penelitian kemudian disusun berdasarkan rumusan masalah yang telah ditetapkan.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Manfaat penelitian mencakup kontribusi yang diharapkan dari hasil penelitian ini, baik secara teoritis maupun praktis. Secara teoritis, penelitian ini dapat menjadi referensi bagi studi-studi selanjutnya. Secara praktis, penelitian ini diharapkan memberikan solusi terhadap permasalahan yang ada. Sistematisasi penulisan skripsi di bagian akhir bab ini memberikan gambaran struktur laporan penelitian secara keseluruhan.",
    },
    {
        id: "bab2",
        title: "Bab 2 Kajian Pustaka",
        content:
            "Bab ini berisi landasan teori dan tinjauan pustaka yang digunakan sebagai referensi dalam penelitian. Landasan teori mencakup konsep-konsep yang mendukung penelitian, seperti teori utama yang digunakan sebagai dasar dalam menganalisis permasalahan. Dengan adanya landasan teori yang kuat, penelitian ini dapat berjalan secara sistematis dan terarah.\n\n" +
            "Tinjauan pustaka dilakukan dengan mengkaji penelitian-penelitian terdahulu yang relevan dengan topik yang diangkat. Hal ini bertujuan untuk memahami bagaimana penelitian sebelumnya telah membahas masalah serupa dan apa kontribusi baru yang dapat diberikan oleh penelitian ini. Melalui perbandingan berbagai penelitian sebelumnya, penelitian ini dapat menentukan celah penelitian yang belum dijelajahi.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Bab ini juga membahas teori-teori yang digunakan dalam penelitian, baik yang mendukung maupun yang berlawanan dengan perspektif yang diambil. Analisis teori yang mendalam akan membantu dalam memahami fenomena yang diteliti dan memberikan argumentasi ilmiah yang kuat untuk mendukung hipotesis atau kesimpulan penelitian.",
    },
    {
        id: "bab3",
        title: "Bab 3 Metodologi Penelitian",
        content:
            "Bab ini menjelaskan metode yang digunakan dalam penelitian, termasuk jenis penelitian, teknik pengumpulan data, teknik analisis data, serta prosedur penelitian yang dilakukan. Pemilihan metode penelitian dilakukan berdasarkan karakteristik permasalahan yang dikaji agar dapat memperoleh data yang valid dan reliabel.\n\n" +
            "Teknik pengumpulan data yang digunakan dalam penelitian ini mencakup wawancara, observasi, dan studi pustaka. Wawancara dilakukan dengan narasumber yang relevan untuk mendapatkan perspektif langsung mengenai topik yang diteliti. Observasi memungkinkan peneliti untuk melihat secara langsung fenomena yang sedang dikaji, sedangkan studi pustaka dilakukan untuk memperkuat dasar teori yang digunakan.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Teknik analisis data melibatkan langkah-langkah seperti reduksi data, penyajian data, dan penarikan kesimpulan. Data yang telah dikumpulkan dianalisis menggunakan pendekatan kualitatif maupun kuantitatif sesuai dengan tujuan penelitian. Dengan metode yang tepat, penelitian ini diharapkan dapat menghasilkan temuan yang akurat dan bermanfaat.",
    },
    {
        id: "bab4",
        title: "Bab 4 Hasil dan Pembahasan",
        content:
            "Bab ini memaparkan hasil penelitian yang telah diperoleh serta pembahasannya berdasarkan teori yang telah dijelaskan sebelumnya. Data yang dikumpulkan dianalisis untuk mengungkap pola, hubungan, dan implikasi yang relevan terhadap masalah yang diteliti. Penyajian data dalam bentuk tabel dan grafik membantu mempermudah interpretasi temuan penelitian.\n\n" +
            "Pembahasan dalam bab ini dilakukan dengan menghubungkan hasil penelitian dengan teori yang telah diuraikan dalam kajian pustaka. Perbandingan antara hasil yang diperoleh dengan penelitian sebelumnya juga dilakukan untuk menilai validitas temuan. Jika terdapat perbedaan atau kesamaan dengan studi sebelumnya, hal tersebut dianalisis secara kritis.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Selain itu, bab ini juga mengidentifikasi faktor-faktor yang berkontribusi terhadap hasil penelitian serta implikasi dari temuan yang diperoleh. Dengan demikian, pembahasan dalam bab ini tidak hanya berfokus pada penyajian data, tetapi juga analisis mendalam mengenai makna dan signifikansi dari hasil penelitian.",
    },
    {
        id: "bab5",
        title: "Bab 5 Kesimpulan dan Saran",
        content:
            "Bab ini menyajikan kesimpulan dari hasil penelitian yang telah dilakukan serta saran untuk penelitian selanjutnya. Kesimpulan disusun berdasarkan temuan utama penelitian yang diperoleh dari analisis data. Setiap kesimpulan yang disajikan berusaha menjawab pertanyaan penelitian yang telah dirumuskan sebelumnya.\n\n" +
            "Selain kesimpulan, bab ini juga memberikan saran yang dapat diterapkan dalam konteks penelitian atau praktik di lapangan. Saran yang diberikan dapat mencakup rekomendasi untuk peningkatan metode penelitian, pengembangan lebih lanjut dari hasil penelitian, atau penerapan temuan dalam dunia nyata.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed nisl a neque interdum pharetra. Vestibulum euismod, urna at faucibus dignissim, justo lacus sollicitudin metus, nec dictum libero quam a lorem. Integer quis risus nec libero fringilla tincidunt. Sed dictum, turpis nec rhoncus suscipit, justo augue hendrerit nisi, ut pharetra mauris velit in augue. Nunc euismod, ipsum et gravida dapibus, eros ex tempor purus, at aliquet nisl eros vel purus. Duis eget tortor ut massa posuere vehicula. Donec venenatis nulla id justo ultricies, non hendrerit odio luctus.\n\n" +
            "Bab ini juga menyoroti keterbatasan penelitian yang mungkin mempengaruhi hasil yang diperoleh. Dengan mengakui keterbatasan tersebut, penelitian selanjutnya dapat dilakukan dengan pendekatan yang lebih komprehensif untuk mendapatkan hasil yang lebih akurat dan mendalam.",
    },
];

const SkripsiOnline: React.FC = () => {
    const [activeSection, setActiveSection] = useState(sections[0].id);

    useEffect(() => {
        const handleScroll = () => {
            const scrollPosition = window.scrollY;

            for (const section of sections) {
                const element = document.getElementById(section.id);
                if (element) {
                    const offsetTop = element.offsetTop;
                    if (scrollPosition >= offsetTop - 100) {
                        setActiveSection(section.id);
                    }
                }
            }
        };

        window.addEventListener("scroll", handleScroll);
        return () => window.removeEventListener("scroll", handleScroll);
    }, []);

    return (
        <div className="relative min-h-screen bg-gray-100 px-4 py-6">
            {/* Navbar */}
            <nav className="fixed top-0 left-0 w-full bg-blue-500 text-white p-4 text-lg font-bold z-50">
                <div className="flex flex-col">
                    <span className="text-sm lg:text-xl">Harist Fadlilah - 232605005</span>
                    <span className="text-sm text-black bg-red-600">{sections.find((s) => s.id === activeSection)?.title}</span>
                </div>
            </nav>

            <div className="mt-16 space-y-8 pt-16">
                {sections.map((section) => (
                    <div key={section.id} id={section.id} className="p-4 bg-white shadow-lg rounded-lg">
                        <h2 className="text-xl font-bold text-blue-700">{section.title}</h2>
                        <p className="mt-2 text-gray-700">{section.content}</p>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default SkripsiOnline;
